version: "3"
services:
  lottodb:
    image: mysql:8.0
    container_name: lottodb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lotto
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: freedom
      MYSQL_PASSWORD: 123
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    networks:
      - lotto-network
    restart: always

  lottodb_admin:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
      - lottodb
    container_name: lottodb_admin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: lottodb
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: freedom
      MYSQL_PASSWORD: 123
    networks:
      - lotto-network

  lotto_web:
    #build: . ถ้า build จากเครื่องตัวเอง
    image: nut077/lotto
    depends_on:
      - lottodb
    container_name: lotto_web
    ports:
      - 8080:8080
    networks:
      - lotto-network
    restart: always

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - lottodb
      - lottodb_admin
      - lotto_web
    command: lottodb lottodb_admin lotto_web
networks:
  lotto-network:

volumes:
  db_data:
